// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gini
DataFrame gini(DataFrame edges, NumericMatrix expression, int bootstrapIterations, double statCutoff);
RcppExport SEXP NECorr_gini(SEXP edgesSEXP, SEXP expressionSEXP, SEXP bootstrapIterationsSEXP, SEXP statCutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type expression(expressionSEXP);
    Rcpp::traits::input_parameter< int >::type bootstrapIterations(bootstrapIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type statCutoff(statCutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(gini(edges, expression, bootstrapIterations, statCutoff));
    return rcpp_result_gen;
END_RCPP
}
