# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropy_weight_cpp <- function(mat) {
    .Call(`_NECorr_entropy_weight_cpp`, mat)
}

multi_corr_necorr <- function(expression, ranks, src, tgt, bootstrapIterations = 0L, useBestGCC = FALSE, asymmetricGCC = FALSE, rownames_in = character()) {
    .Call(`_NECorr_multi_corr_necorr`, expression, ranks, src, tgt, bootstrapIterations, useBestGCC, asymmetricGCC, rownames_in)
}

compute_TSI_TSE_parallel <- function(expr) {
    .Call(`_NECorr_compute_TSI_TSE_parallel`, expr)
}

