# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do values in a numeric vector fall in specified range?
#'
#' This is a shortcut for `x >= left & x <= right`, implemented
#' efficiently in C++ for local values, and translated to the
#' appropriate SQL for remote tables.
#'
#' @param edges dataframe with the edges with 3 columns: source, interaction and
#' target
#' @param expression, expression table containing the genes
#' @param bootstrapIterations number of bootstrap
#' @param statCutoff stat cut-off p-value
#' @export
gini <- function(edges, expression, bootstrapIterations, statCutoff) {
    .Call(`_NECorr_gini`, edges, expression, bootstrapIterations, statCutoff)
}

