---
title: "README"
author: "Christophe Liseron-Monfils"
date: "7/5/2018"
output: html_document
---

# Network Correlation Analysis (NECorr)

## Contents

- [Overview](#overview)
- [Repo Contents](#repo-contents)
- [System Requirements](#system-requirements)
- [Installation Guide](#installation-guide)
- [Instructions for Use](#instructions-for-use)
- [License](./LICENSE)
- [Pseudocode](#pseudocode)
- [Citation](#citation)
# Overview

NECorr is a R package based on multiple-criteria decision-making algorithms. With the objective of ranking genes and their interactions in a selected condition or tissue, NECorr uses molecular network topology as well as global transcriptomics analysis to find condition/tissue-specific hub genes and their regulators.

# Repo Contents

- [R](./R): `R` package code.
- [docs](./docs): package documentation.
- [man](./man): package manual for help in R session.
- [tests](./tests): `R` unit tests written using the `testthat` package.


# System Requirements

## Hardware Requirements


The runtimes below are generated using a computer with the recommended specs (16 GB RAM, 4 cores@3.3 GHz) and internet of speed 25 Mbps.

## Software Requirements

### OS Requirements

This package is supported for *Linux* operating systems. The package has been tested on the following systems:

Linux: Redhat RHEL 7.4  
Mac OSX: OS X 10.13.5


The NECorr packages requires the R version 3.3.1 (2016-06-21) or higher and a standard computer with enough RAM to support the operations defined by a user. For minimal performance, this will be a computer with about 1 GB of RAM. 

#### Installing R version 3.4.2 on Ubuntu 16.04

the latest version of R can be installed by adding the latest repository to `apt`:

```
sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
gpg -a --export E084DAB9 | sudo apt-key add -
sudo apt-get update
sudo apt-get install r-base r-base-dev
```

which should install in about 20 seconds.

#### Package dependencies

Users should install the following packages prior to installing `mgc`, from an `R` terminal:

```
install.packages(c(Rcpp, RcppParallel, klaR, igraph, dnet, foreach, doSNOW, RColorBrewer, gplots, devtools))
source("https://bioconductor.org/biocLite.R")
biocLite(c("Biobase", "limma"))

```

#### Package Versions

The `mgc` package functions with all packages in their latest versions as they appear on `CRAN` on October 15, 2017. Users can check [CRAN snapshot](https://mran.microsoft.com/timemachine/) for details. The versions of software are, specifically:
```
Rcpp:
klaR:
igraph:
dnet:
foreach:
doSNOW:
RColorBrewer:
gplots:
devtools:
Biobase:
limma:
```

If you are having an issue that you believe to be tied to software versioning issues, please drop us an [Issue](https://github.com/neurodata/mgc/issues). 

# Installation Guide

From an `R` session, type:

```
require(devtools)
install_github('neurodata/mgc', build_vignettes=TRUE)  # install mgc with the vignettes
require(mgc)  # source the package now that it is set up
vignette("MGC", package="mgc")  # view one of the basic vignettes
```

The package should take approximately 20 seconds to install with vignettes on a recommended computer. 


### Instructions for Use

Please see the vignettes for help using the package:

```
vignette("MGC", package="mgc")
vignette("discriminability", package="mgc")
vignette("sims", package="mgc")
```


# Pseudocode

Pseudocode for the methods employed in the `mgc` package can be found on the [arXiv - MGC](https://arxiv.org/abs/1609.05148) in Appendix C (starting on page 30).

# Citation

For citing code or the paper, please use the citations found in [citation.bib](./citation.bib).

